### PR TITLE
Adding __init__.py to avoid module not found errors

### PR DESCRIPTION
**Pull request by chris-alexiuk**
When pip installing, I was running into some module not found errors. This should resolve those. 

Sorry if I missed a reason they weren't included.

### CODE REVIEW

**Comment by jpgard** [comment]
This shouldn't be necessary. As of Python 3.3, Python does not require __init__.py for the package to be importable. Are you using the conda environment we provide via `environment.yml`?

**Comment by anas-awadalla** [comment]
@chris-alexiuk I am able to reproduce the issue. Thanks for letting us know! I am testing your branch and will merge.

**Comment by jpgard** [comment]
thank you for the PR @chris-alexiuk ! sorry for my confusion.

**Comment by chris-alexiuk** [comment]
Absolutely no worries! Thanks for double-checking!

**Pull request merged**
